#!/bin/bash
# A script to insert into the user data field of an AWS EC2 instance running on Ubuntu to launch and configure an apache webserver

# Initial update and installing apache
sudo apt update -y
sudo apt install -y apache2 

# Starting and enabling apache
sudo systemctl start apache2
sudo systemctl enable apache2

# Create a simple index page
echo "<h1>Apache Web Server Running on Ubuntu!</h1>" | sudo tee /var/www/html/index.html
